version: '3'

services:
  api:
    build: ./api
    ports:
      - '3001:3001'
    command: npm run server
    restart: always

  app:
    build: ./
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app
    restart: always
    depends_on:
      - api
